### ISSUE TITLE
Autogenerated schema does not generate mutaton queries correctly.

### ISSUE THREAD

**Issue by georgyo** [profusion/sgqlc#102]
Queries generated with a schema.Mutation are missing the `mutation { }` wrapping them.

Example
1. Generated Schema
 ```
python3 -m sgqlc.introspection \
  --exclude-deprecated \
  https://apps.cloudhealthtech.com/graphql \
  ch_schema.json

sgqlc-codegen ch_schema.json ch_schema.py
```
2. Run the following python
```
#!/usr/bin/env python3
from sgqlc.operation import Operation
from ch_schema import ch_schema as schema

login = Operation(schema.Mutation).login_api(api_key="foo")
print(login)
```
Which returns
```
loginAPI(apiKey: "foo") {
  accessToken
  idToken
  refreshToken
}
```

However the expected output should be
```
mutation {
  loginAPI(apiKey: "foo") {
    accessToken
    idToken
    refreshToken
  }
}
```

**Comment by barbieri** [comment]
I'll take a look, but did you try to print `operation` instead of the `login`?

```py
op = Operation(schema.Mutation)
op.login_api(api_key="foo")
print(op)
```

The call you said will return the `login` selection, not the root (operation), then printing it would print just that subtree...

**Comment by georgyo** [comment]
Ah, that does work! But not all that intuitive. 

```
#!/usr/bin/env python3

from sgqlc.endpoint.http import HTTPEndpoint
from sgqlc.operation import Operation
from ch_schema import ch_schema as schema

op = Operation(schema.Mutation)
op.login_api(api_key="foo")
print(op)
```
Generated the correct output
```
mutation {
  loginAPI(apiKey: "foo") {
    accessToken
    idToken
    refreshToken
  }
}
```

Thank you for your help!

**Comment by barbieri** [comment]
well, there is no way to magically solve the issue... in more real world examples where you'd need to query more fields, you need to keep the reference to the parent to call (select) each member you want to retrieve.

and in some cases you do want to print only the subtree... then I cannot simply automatically go to the root in order to print the full document.

If you have any suggestions on how to improve that without breaking the other cases, let me know! Otherwise please close the issue :-)

**Comment by georgyo** [comment]
What I would expect is that something like  `op = Operation(schema.Mutation).login_api(api_key="foo")` to return the root of operation.

And I would expect the following op is just `mutation {}` and login is the full operation.

```
op = Operation(schema.Mutation)
login = op.login_api(api_key="foo")
```
consider the following code
```
foo = "hello"
bar = foo.upper()
```

You would not expect upper to have a side effect on foo. Granted there are plenty of cases where side effects do happen (set, insert, append, pop, etc), but it is clearer that is what you want.

The benefit to returning a new object instead of modifying the pervious object is that you could reuse sections of the code.

```
mut = Operation(schema.Mutation)
login_resp = endpoint(mut.login_api(api_key="foo"))
foo_resp = endpoint(mut.foo())
```

instead that currently must be written as

```
op =  Operation(schema.Mutation)
op.login_api(api_key="foo")
login_resp = endpoint(op)

op = Operation(schema.Mutation)
op.foo()
foo_resp = endpoint(op)
```

Anyway, this is all a matter of personal preference. So feel free to close this ticket if it is working as expected.

This library is pretty excellent and is making my life easier today.

**Comment by barbieri** [comment]
While I get your idea, it's a usability issue. With your rationale, we'd not be able to select nested fields easily, because once you select it, you'd not get to the parent object, would always go to the root. Try to work on more realistic examples, with many nested fields, arguments... You want to send the whole operation, composed of multiple fields.

In your example with `login_resp` and `foo_resp` is exactly what GraphQL helps to avoid, you'd never do 2 requests, just do one! With both queries encoded in one go ;-)
