### ISSUE TITLE
Do we have any example code for fetching data from multiple tables?

### ISSUE THREAD

**Issue by gu3sss** [profusion/sgqlc#105]
Do we have any example code for fetching data from multiple tables?

**Comment by barbieri** [comment]
what do you mean with tables? GraphQL doesn't have any tables

**Comment by gu3sss** [comment]
Apologies for lack of clarity in my question! I am fairly new to Graphql and the terminologies in Graphql world are new to me. Here's my use case, 

- I have an API which receives query params from end user
- The API's backend is a Python application which consumes the request, parses the query params, fetches data from a backend MySql Db and returns it to the user as the API response.
- I am using SqlAlchemy as the ORM to interact with Db
- Graphene-SqlAlchemy for building the Graphql Schema and queries to fetch data from Db
- SGQLC to dynamically generate the Graphql queries in runtime based on the query params

The issue am facing now is that, 

- I have 2 tables in Db (PipelineMain and PipelineAccess) and my GraphQl schema is written in a way to fetch data individually from these 2 tables.
- I am unable to write the schema in a way to fetch data from both tables using joins. For example, if PipelineMain table has 2 columns (pipeline_name and pipeline_id) and PipelineAccess table has 2 columns (pipeline_id and user_info), I would like my GraphQl schema to be able to generate query that can display all pipeline_name from PipelineMain table for a given user in PipelineAccess.

I guess this is more of a question for the broader GraphQl community. My apologies of this is not the write forum. I raised this question here thinking that it was related to SGQL initially.

**Comment by barbieri** [comment]
Hi,

Indeed this part has nothing to do with the client library. However, on the schema you should never expose just ids and try to correlate tables like that. Instead you expose the actual field. From your example, you'd have the following schema:

```gql
type Pipeline implements Node { # your Pipeline Main, "implements Node" is not strictly required, but recommended
  id: ID! # recommended by Node, but this should be a global id, not your raw DB id. Usually encode as `tableName:id` or something like that, with decode/parse validation
  name: String # your pipeline_name
  accesses: [PipelineAccess!] # lists all access in a Pipeline -> this resolver will do a SELECT on the other table
}

type PipelineAccess implements Node {
  id: ID!
  userInfo: UserInfo
  # some more fields here, like "isAdmin/role", "createdAt"...
  pipelines: [Pipeline!] # lists all pipelines for a given access -> this resolver will do a SELECT on the other table
}

type UserInfo implements Node {
  id: ID!
  name: String
  pipelinesAccesses: [PipelineAccess!] # list all pipelines access this user have -> this resolver will do a SELECT on the other table 
}

# common toplevel queries:
type Query {
  node(id: ID!): Node # fulfills all "byId" queries one would write
  pipelines: [Pipeline!]
  pipelinesAccesses: [PipelineAccess!]
}
```

With the above, your GraphQL queries would be something like:

```gql
query {
  node(id: "someUserId") {
    ... on UserInfo { # this fragment is required, according to GQL rules (same as type-check in languages, "is instance of")
      name # the user name
      pipelinesAccesses { # this does a SELECT ... FROM PipelineAccess WHERE userId = ...
         pipeline { # this does a JOIN
            name
         }
      }
    }
  }
}
```

This is the recommended Graph pattern that the Query Language (Graph-Query-Language) is built on, you "navigate" to the information you want: get a user, list its pipeline accesses, then select the pipeline, then select its name.

The GQL standard doesn't state how this will map to the backing store, like your DB/ORM. You could be naive and do multiple queries, one for each field, in this case it would generate a huge number of queries (one to get the user, another to list the pipeline accesses, then another for each pipeline access to get the pipeline name). In practice people use one of the 2 approaches bellow:

1. instead of processing each field resolver individually, process the whole query using the AST and generate one big SQL with the JOIN to select the final fields. This is tempting for efficiency, but it may blow in complexity.  You may look at this project (JavaScript, but does that): https://join-monster.readthedocs.io/

2. use a DataLoader pattern (ie: https://docs.graphene-python.org/en/latest/execution/dataloader/), then you'd still use individual resolvers as the naive version, but the `batch_load_fn` will queue all the `id` you want to load and call you once, so you can do a single DB query. It will result in more queries (ie: 2-3 in the example above), but this is much better than the unlimited number of queries in the naive version, while being **much, much simpler to implement**.

**NOTE:** these list queries should all be paginated in practice, unless you have some guarantees they will be reasonably short.

**Comment by gu3sss** [comment]
Thanks a lot for detailed explanation! Based on the examples I referred in Graphene and SGQLC github pages, here's what I have now.

- graphql_schema.py - the main GQL schema file
- graphql_filter.py - file to maintain filters
- graphql_sgqlc_schema.py - the schema file generated by SGQLC Code generator using the introspection result and above main schema file
- graphql_queries.py - file where a bunch of dynamic GQL queries are derived based on the generated SGQLC schema file

PFA the same - [Graphql_files.zip](https://github.com/profusion/sgqlc/files/4843317/Graphql_files.zip)

I will review your suggestions and try modifying my code.

**Comment by barbieri** [comment]
is it solved? should we close the issue?

**Comment by gu3sss** [comment]
Thanks for the help @barbieri
