### ISSUE TITLE
Copying instance of Operation

### ISSUE THREAD

**Issue by ar-ms** [profusion/sgqlc#79]
Hello, I'm trying to copy an operation instance, so I can use it as a base query in order to paginate. But when I do so using `copy`, it terminates with a RecursionError like in #58 . Is there a good way to do it ?

**Comment by barbieri** [comment]
copy is not supported, but in your case you should use a variable, then you just send the new variables for each pagination request.

https://github.com/profusion/sgqlc/blob/master/sgqlc/types/__init__.py#L1973
https://github.com/profusion/sgqlc/blob/master/sgqlc/operation/__init__.py#L1685

instead of using `field(first=1)` you should use `field(first=Variable('first'))`, then in your call you pass the variables https://github.com/profusion/sgqlc/blob/master/sgqlc/endpoint/http.py#L96

**Comment by ar-ms** [comment]
I started to check Variable, thanks a lot for pointing the different resources !

**Comment by zevisert** [comment]
Why isn't `copy` or `deepcopy` supported? For me, that makes it hard to test applications using sgqlc, when the endpoint is mocked using a `MagicMock`. The main problem is that the library encourages using a (mutable) dictionary as the second argument, but unittest only keeps references to call arguments.

**Comment by barbieri** [comment]
well, I never had a clear use, as it was not written to be copyable, trying to add it later is likely to cause bugs, unless we can test it extensively.

But I fail to see how copy/deepcopy would interfere with testing. Could you elaborate more?  Usually one create an operation, cache the byte/string representation to send to server. Then use the operation to interpret data (`__add__` operator), which can be done multiple times. If there is a need to add parameters change change from one to another, using `Variable` is the way to go (for multiple reasons).

For some reason you can't cope with that, you can always write a function that re-creates the same operation over and over again... there is no good to copy compared to just re-create it. If you use `sgqlc-codegen operation` you get these functions, they just re-create the operations when called.
