### ISSUE TITLE
Add __version__ module attribute and set patch number

### ISSUE THREAD

**Issue by plorenzatto** [profusion/sgqlc#84]
It would be useful to add a `__version__` module attribute according to [PEP 396](https://www.python.org/dev/peps/pep-0396/).

Also it would be help to have a patch number along the major and minor version.

**Comment by barbieri** [comment]
good!

As for patch version, I'm not using it myself, I tried to keep major numbers only (since this is a small project without many changes, it would be stuck with the major version forever).

However to make it clear the changes are minor, like small bugfixes and all, I started to introduce minor versions later on.

**Comment by barbieri** [comment]
released as v10.0, see https://pypi.org/project/sgqlc/10.0/
